name = "theme-extension"
type = "theme"
uid = "65b30aae-2fc0-9b48-3e28-e6bf3e801b92f9c75ad7"

[[blocks]]
name = "Metafield Display"
type = "product"
target = "section"
file = "blocks/metafield-display.liquid"
